name: Deploy Flask Calculator and Converter to AWS Elastic Beanstalk

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Zip application
        run: zip -r flask-app.zip * .[^.]*

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-1" # Replace with your AWS region (e.g., ap-southeast-1 for Singapore, which is closer to Penang)

      - name: Create application version
        id: create-version
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          VERSION_LABEL="flask-app-$TIMESTAMP-$GITHUB_SHA"
          aws elasticbeanstalk create-application-version \
            --application-name "your-beanstalk-app-name" \ # Replace with your Elastic Beanstalk application name
            --version-label "$VERSION_LABEL" \
            --source-bundle S3Bucket="your-beanstalk-bucket-name",S3Key="flask-app.zip" # Replace with your S3 bucket name

      - name: Update environment
        run: |
          aws elasticbeanstalk update-environment \
            --application-name "your-beanstalk-app-name" \ # Replace with your Elastic Beanstalk application name
            --environment-name "your-beanstalk-env-name" \   # Replace with your Elastic Beanstalk environment name
            --version-label "${{ steps.create-version.outputs.VERSION_LABEL }}"
